config/routes.rb
Rails.application.routes.draw do
  get 'search/create'

resources :products

  devise_for :users
  get 'welcome/index'

  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products=Product.all
  end

  def new
    @product=Product.new
  end
  def create
    @product=Product.new(set_params)
    @product.save
  end

  private
  def set_params
    params.require(:product).permit(:name, :price, :description, :code, :unity, :code, :provider)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def create

     code = params[:keyword]

     @product=Product.find_by("code", code)

     if(@product)
          puts "exist #{@product.code}"
     else
          puts "not_exist"
     end

     respond_to do |format|
      format.json { render json: @product }
      format.html { redirect_to root_path }
      format.js
      #rails buscara un archivo create.js en relacion con el controlador
    end


  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pos</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>




  <header>
    <nav>
      <ul>
        <li><%= link_to('Inicio', root_path ) %></li>
        <% if (user_signed_in?)%>
        <li><%= link_to('Edit profile', edit_user_registration_path(current_user) ) %></li>
        <li><%= link_to('Logout', destroy_user_session_path, method: :delete  ) %></li>

        <% else %>
        <li><%= link_to('Login', new_user_session_path ) %></li>
        <li><%= link_to('Register', new_user_registration_path ) %></li>
        <% end %>

        <li><%= link_to('products', products_path)%></li>

      </ul>
    </nav>
  </header>




  <div class="content wrapper">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </div>


</body>
</html>

app/views/products/_product.html.erb
<tr>
  <td><%= @product.name%></td>
  <td><%= @product.code%></td>
  <td><%= @product.price%></td>
</tr>

app/views/products/index.html.erb
List of products





<div class="">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>

      <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price%></td>
      </tr>

      <% end %>

    </tbody>
  </table>

</div>

app/views/products/new.html.erb
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="col-sm-3">
    <div>
      <%= f.label :name %>

    </div>
    <div>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="col-sm-3">
    <div>
      <%= f.label :description %>

    </div>
    <div>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
  </div>
  <div class="col-sm-3">
    <div>
      <%= f.label :provider %>

    </div>
    <div>
      <%= f.text_field :provider, class: 'form-control' %>
    </div>
  </div>
  <div class="col-sm-3">
    <div>
      <%= f.label :unity %>

    </div>
    <div>
      <%= f.text_field :unity, class: 'form-control' %>
    </div>
  </div>

</div>

<div class="row">
  <div class="col-sm-3">

    <div>
      <%= f.label :price %>

    </div>
    <div>
      <%= f.number_field :price ,  class: 'form-control' %>
    </div>
  </div>

  <div class="col-sm-3">
    <div>
      <%= f.label :code %>
    </div>
    <div>
      <%= f.number_field :code, class: 'form-control' %>
    </div>
  </div>
</div>



<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/welcome/index.html.erb
<div class="detail-pos">

  <div class="detail-pay border-details">
    <div class="information">

    </div>
    <div class="">

      <%= form_tag "/search/create", method: :get, remote: true, id: "search-form" do %>
      <%= text_field_tag :keyword, nil, placeholder: " Qué estás buscando" %>
      <%= content_tag :button, type: :submit do %>
      Buscar
      <% end %>
      <% end %>

    </div>

  </div>
  <div class="detail-buy border-details">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Firstname</th>
          <th>Lastname</th>
          <th>Email</th>
        </tr>
      </thead>
      <tbody id="results">





      </tbody>
    </table>

  </div>

</div>